# Site settings
title: Out of memory
# email: your-email@domain.com
description: "b3V0IG9mIG1lbW9yeQ=="
baseurl: ""
url: "http://localhost:4000"
# twitter_username: lmarqueta
# github_username:  lmarqueta

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
